### PR TITLE
Update META6.json

### PR DESCRIPTION
**Pull request by kjkuan**
- [X] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by jonathanstowe** [comment]
Looks fine from here.

**Comment by jonathanstowe** [comment]
Oh, it's actually failing its tests.

**Comment by kjkuan** [comment]
probably because the system on which it ran the tests doesn't have `/bin/bash`.
I'll have to rewrite or skip some of the tests.

**Comment by JJ** [comment]
It's an Alpine, and it does have /bin/bash, although it's really an alias for /bin/sh, a simplified shell. It's the package tests the one that fails, and also the META6.json seems to have another error. Can you please check?

**Comment by kjkuan** [comment]
@JJ I've adapted the tests. How do you trigger a rebuild from this PR?

**Comment by JJ** [comment]
I'll go to travis and spin it again

**Pull request merged**
