### PR TITLE
Add Algorithm::KdTree to ecosystem

### PR DESCRIPTION
**Pull request by okaoka**
See https://github.com/okaoka/p6-Algorithm-KdTree

### CODE REVIEW

**Comment by skaji** [comment]
AFAIK, you need to specify resources in META6.json.

cf
https://github.com/retupmoca/P6-LibraryMake/issues/17
https://github.com/hoelzro/p6-native-resources
https://github.com/skaji/perl6-librarymake-example

**Comment by okaoka** [comment]
Sorry, I forgot that.
I will fix it soon.

**Comment by skaji** [comment]
oh, just FYI :)

**Comment by jonathanstowe** [comment]
Thanks!

**Comment by okaoka** [comment]
@jonathanstowe thanks for merge! 

@skaji Sorry it will take more time than I thought.
According to your advice, I'm trying to use "Native::Resources".
But I'm facing 2 problems.

#### Compile-time variable `%?RESOURCES` seems does not work
+ running test
```
$ mi6 test
===SORRY!===
Type check failed in binding %RESOURCES; expected Associative but got Nil
```

It seems that Native::Resources couldn't read a variable `%RESOURCES` or a variable `%RESOURCES` isn't being set using `META6.json` in my environment (Debian wheezy).

#### Native::Resouces incapacitate App::Mi6 from generating `README.md`
+ I don't know what to do... :bird:

**Pull request merged**
