### PR TITLE
Add Bio::ViennaNGS

### PR DESCRIPTION
**Pull request by mtw**
- [X] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by jonathanstowe** [comment]
``` no source-url defined in META file```

**Comment by mtw** [comment]
sorry guys, this is my first Perl6 module. Updated META6.json accordingly

**Comment by jonathanstowe** [comment]
It's missing the comma after the "support" object, you might find it useful to install ```Test::META``` and have an optional test to check your META file.

**Comment by mtw** [comment]
just realized that. thx for the Test::META hint.

**Pull request merged**
