### PR TITLE
Add Net::RCON module to P6 ecosystem

### PR DESCRIPTION
**Pull request by kawaii**
- [X] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses

### CODE REVIEW

**Comment by Altai-man** [comment]
According to documentation, something like ` "git://github.com/you/Vortex-TotalPerspective.git"` has to be a "source-url" value.
So `git://github.com/shuppet/p6-net-rcon.git` should do.

**Comment by kawaii** [comment]
@Altai-man ah, thanks! I've updated the `master` branch on the repository to reflect this.

**Comment by Altai-man** [comment]
Ok, I've triggered the build.

**Comment by Altai-man** [comment]
```
        # file for 'Net::RCON' 'lib/API/RCON.pm6' does not exist
        not ok 4 - 'provides' looks sane
        # Failed test ''provides' looks sane'
```
Oops.

**Comment by kawaii** [comment]
@Altai-man good catch, fixed. One last build should do it. :)

**Pull request merged**
