### PR TITLE
Transfer of two modules

### PR DESCRIPTION
**Pull request by MARTIMM**
Update proposal because of transfer of two modules from bbkr to MARTIMM

### CODE REVIEW

**Comment by FROGGS** [comment]
does @bbkr agree?
@MARTIMM you'd also need to adjust the source urls in:
https://raw.githubusercontent.com/MARTIMM/BSON/master/META.info
https://raw.githubusercontent.com/MARTIMM/mongo-perl6-driver/master/META.info

Otherwise panda might complain.

**Comment by vendethiel** [comment]
@FROGGS Seems like he agrees:

MARTIMM/BSON@99989123a27b0c06af8f10820da0ef2da378a040

**Comment by FROGGS** [comment]
awesome :o)

**Comment by moritz** [comment]
@MARTIMM I've also invited you to the perl6 github org, so that you can push yourself in future

**Comment by bbkr** [comment]
"does @bbkr agree?"

Yes. Those modules were stalled since 2012 (I've stopped using MongoDB) and MARTIMM++ made them run on latest Rakudo again \o/

Thanks.

**Comment by bbkr** [comment]
MARTIMM: don't forget to change also CONTACT section as mentioned here:

https://github.com/MARTIMM/mongo-perl6-driver/pull/3

**Comment by MARTIMM** [comment]
I still have to that. Will be ready soon. Thanks for mentioning again

**Pull request merged**
