### PR TITLE
Add Router::Right to ecosystem

### PR DESCRIPTION
**Pull request by pheix**
See https://gitlab.com/pheix/router-right-perl6

🦋🦋🦋

- [X] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by Altai-man** [comment]
Thanks!

**Comment by zoffixznet** [comment]
@pheix I sent you an invite to **perl6** GitHub org. You can accept it here: https://github.com/perl6/

That gives you a commit bit to most of our repos and you can commit further additions directly.

**Comment by pheix** [comment]
Thanks for merge!

**Comment by pheix** [comment]
@zoffixznet, great!

**Comment by pheix** [comment]
@Altai-man, there was a bug in META6.json at source-url section: https://gitlab.com/pheix/router-right-perl6/blob/9d1a9fcbf69b6c455bcb5621a7e599c2dc1f909b/META6.json, url is wrong. This url is migated to http://ecosystem-api.p6c.org/projects.json, so install via zef fails.

I have fixed this on v0.0.43 - please update projects.json

Thank you and sorry for the typing error 🙄🙄🙄

**Comment by pheix** [comment]
I think [project.json](http://ecosystem-api.p6c.org/projects.json) file is auto-updatable, now everything ok with zef install.

```sh
[kostas@webtech ~]$ zef update
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects1.json
----------------------------------------------------
Content Storage                  |Distribution Count
----------------------------------------------------
Zef::Repository::Ecosystems<p6c> |881               
Zef::Repository::Ecosystems<cpan>|667               
Zef::Repository::LocalCache      |9                 
----------------------------------------------------
[kostas@webtech ~]$ zef search Router::Right
===> Found 1 results
-------------------------------------------------------------------------------------------------------------------------------------
ID|From                            |Package                  |Description                                                            
-------------------------------------------------------------------------------------------------------------------------------------
0 |Zef::Repository::Ecosystems<p6c>|Router::Right:ver<0.0.43>|Perl6-based, framework-agnostic URL routing engine for web applications
-------------------------------------------------------------------------------------------------------------------------------------
[kostas@webtech ~]$ zef install Router::Right
===> Searching for: Router::Right
===> Searching for missing dependencies: P5quotemeta
===> Testing: P5quotemeta:ver<0.0.3>:auth<cpan:ELIZABETH>
===> Testing [OK] for P5quotemeta:ver<0.0.3>:auth<cpan:ELIZABETH>
===> Testing: Router::Right:ver<0.0.43>
===> Testing [OK] for Router::Right:ver<0.0.43>
===> Installing: P5quotemeta:ver<0.0.3>:auth<cpan:ELIZABETH>
===> Installing: Router::Right:ver<0.0.43>
[kostas@webtech ~]$
```

**Comment by Altai-man** [comment]
>I think project.json file is auto-updatable, now everything ok

It is. :)

I have checked the module locally by plain cloning and doing `zef install .`, as it sometimes occurs for modules to be un-installable for various reasons. If it works locally - then we can fix it on net too, but not the other way.

**Pull request merged**
