### PR TITLE
Update META.list with the BCP57 module

### PR DESCRIPTION
**Pull request by alabamenhu**
- [X] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by jonathanstowe** [comment]
Hi,
I think the line ```"Intl:BCP47"          : "lib/BCP47.pm6"``` in your META6.json is wrong.  Did you mean ```ib/Intl/BCP47.pm6```?

**Comment by Altai-man** [comment]
I'm fixing the module right now, just wait for a bit...

**Comment by alabamenhu** [comment]
Yes, I'm an idiot (two typos in the same JSON file *sigh*).

I've updated the JSON file now.

Thanks for the heads up!

**Comment by Altai-man** [comment]
I have fixed metadata in https://github.com/alabamenhu/BCP47/pull/1/
so even without travis check this can be merged after the PR merge.

**Comment by Altai-man** [comment]
Merged(I assume it's safe to not wait for travis, crucify me tomorrow otherwise). @alabamenhu++.

**Comment by Altai-man** [comment]
Uhm, last night `zef test .` and `zef install .` was clean on my local machine. That's why I merged it. What is exact error?

**Comment by JJ** [comment]
Check [above](https://travis-ci.org/perl6/ecosystem/builds/496184954?utm_source=github_status&utm_medium=notification), I think one file is not where it should be...

**Comment by Altai-man** [comment]
`Failed to open file /tmp/Intl__BCP47/lib/BCP47.pm6: No such file or directory` it seems to me like travis had the obsolete repo version, as this error(along with others) was fixed with the PR above.

**Comment by JJ** [comment]
This has been happening a couple of times... I have no idea if it's a Travis error or what.

**Comment by JJ** [comment]
@alabamenhu can you please re-submit?

**Pull request merged**
