### PR TITLE
add p6-Path-Canonical

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by jonathanstowe** [comment]
Thanks

**Comment by labster** [comment]
Going to merge, but have you looked at $*SPEC.canonpath?  Or the other IO::Spec classes? Can you tell me if there's a use case I've missed?

**Comment by mattn** [comment]
Sorry, it should be META6.info. I'll send p-r again.

`$*SPEC.canonpath` require file exists in real. but not on P::C.

**Comment by mattn** [comment]
Ah, sorry. perl5's SPEC require the exists. But perl6's one doesn't ...

**Comment by labster** [comment]
I wrote the IO::Spec classes (mostly ported from Perl 5).  So let me know if there's something you think belongs in the core language, or need something useful for your module.  Thanks!

**Pull request merged**
