### PR TITLE
add Log::Async

### PR DESCRIPTION
**Pull request by bduggan**
Add Log::Async.  See https://github.com/bduggan/p6-log-async

### CODE REVIEW

**Comment by zoffixznet** [comment]
Thanks a lot!

**Comment by jonathanstowe** [comment]
Strangely this is similar to https://github.com/jonathanstowe/Lumberjack but hey the more the merrier :)

**Comment by timo** [comment]
One is for people who want a module that does what it says on the tin,
one is for people who like wordplay and clever puns

**Comment by jonathanstowe** [comment]
I tend to choose names for things that are probably not to be considered the state of the art in a particular domain so they don't block out any potentially sensible names ;-)

**Comment by bduggan** [comment]
Nice!  Thanks for pointing it out -- I hadn't looked into Lumberjack.

**Pull request merged**
