### PR TITLE
CHANGED: v1.0.2

### PR DESCRIPTION
**Pull request by nkh**

### CODE REVIEW

**Comment by AlexDaniel** [comment]
What about having a separate stable branch? This way there would be no need to create a pull request every time there is a new version.

**Comment by nkh** [comment]
I was thinking about having an unstable branch :)

I'll look into it to reduce the load .

N

**Comment by AlexDaniel** [comment]
Thank you!

Well, it is completely up to you which branch should be considered stable. Usually I prefer unstable master and a separate “stable” branch, but of course it could be done other way round.

**Comment by nkh** [comment]
That's what I prefer too,having a specific "stable" branch. I did express
it in the wrong way.

I will be in my next release and that will be in a month at least, I don't
have time to release before holidays, pitty, the possibility to diff data
structures side by side just made it in.

N.

**Pull request merged**
