### PR TITLE
Rename Perl 6 scripts to be .p6

### PR DESCRIPTION
**Pull request by Altai-man**
An attempt to fix https://github.com/perl6/ecosystem/issues/392
The whole conversation diverged a lot, but the original intention is to have Perl 6 script to have Perl 6 script extension.

I have grep'd for all `.pl` scripts and checked those two I found are written in Perl 6.
I also grepped for those file names, but they are not used in other files in this repo.
Of course, let it pass a travis test to see if something from the outside can be broken by this.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
@Altai-man maybe it's time we submit PRs to all ecosystem modules :)

**Comment by Altai-man** [comment]
You mean the `.pm` into `.pm6` conversion? Totally agreed.

In Comma we have a bug report that "Comma is broken, nothing works with `JSON::Tiny` module", but in fact this module uses `.pm` as a file extension and Comma just doesn't recognizes it as Perl 6.

**Comment by AlexDaniel** [comment]
@Altai-man yes, and also maybe .pl → .p6.

**Comment by JJ** [comment]
But are those scripts used from somewhere? Shouldn't you change where they are called too?

**Comment by Altai-man** [comment]
@JJ well, they are totally used in your docker image, so the check fails now. I am sending a PR.
If anyone uses a custom setup, well... It is a question of how much breakage allowance we can have.
These two are basically two scripts for this exact github ecosystem, not CPAN one. And if someone hosts a custom ecosystem for enterprise purposes, I have a feeling that such scripts used for testing PRs will be replaced with something else.

**Pull request merged**
