### PR TITLE
Add AWS::Pricing to ecosystem

### PR DESCRIPTION
**Pull request by scmorrison**
AWS Price List API library

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Thanks!

By the way, it looks like the tests are green even though it failed, what's up with it?

**Comment by scmorrison** [comment]
Thanks. The tests are working on my local system, but see that they are failing in a clean environment. Looking into it now.

**Comment by scmorrison** [comment]
Ok, looks like all the issues are resolved. For some reason modules.perl6.org is displaying "not set up" for Travis, but everything is passing correctly now.

**Comment by zoffixznet** [comment]
Please open an Issue on https://github.com/perl6/modules.perl6.org

**Comment by zoffixznet** [comment]
> For some reason modules.perl6.org is displaying "not set up" for Travis, but everything is passing correctly now.

Should be fixed on the next rebuild that'll complete in about 2 hours from now.

**Pull request merged**
