### PR TITLE
Add tobs' modules

### PR DESCRIPTION
**Pull request by taboege**
- [X] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by JJ** [comment]
There seems to be a problem with finding stuff. Can you please check?

    # Failed test 'SAT::Solver::MiniSAT module can be use-d ok'

**Comment by taboege** [comment]
Ah, and there will probably be a second thing that I totally forgot about and which isn't just a chicken-egg-problem. Some of these modules have git submodules that are needed by their `Build.pm`s. I will have to figure out how to ask the module installer to check them out before attempting to build the module and come back later.

**Comment by JJ** [comment]
maybe use git subtrees instead of submodules?

**Comment by taboege** [comment]
Ok, I've got the second problem fixed. Now it's just the chicken-and-egg problem with the modules depending on each other.

**Comment by taboege** [comment]
Yes, **circular** dependencies do not exist among the modules. It's this PR that kind of depends on itself. The trimmed PR is coming up.

**Pull request closed without merging**
