### PR TITLE
Add Intl-CLDR

### PR DESCRIPTION
**Pull request by alabamenhu**
Add the CLDR module

- [X] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by Altai-man** [comment]
Why is it closed?

**Comment by JJ** [comment]
It failed the test.

You don't need to close it, you can fix it on your side and ping us so that
we launch the tests again.

**Comment by alabamenhu** [comment]
@JJ Ah, I didn't realized I could do that.  Noted for the future

**Comment by JJ** [comment]
No problem.

**Pull request closed without merging**
