### PR TITLE
Add Gumbo to ecosystem

### PR DESCRIPTION
**Pull request by Skarsnik**
See https://github.com/Skarsnik/perl6-gumbo

### CODE REVIEW

**Comment by zoffixznet** [comment]
As I recall, our module system won't parse your `source-url` in META.json correctly. It needs `.git` at the end: `"source-url" : "git://github.com/Skarsnik/perl6-gumbo.git"`

**Comment by jonathanstowe** [comment]
Also, need quotes around "XML" in the depends

**Comment by Skarsnik** [comment]
Should I put the dep to NativeCall too. Or it's considered in the core?

**Comment by jonathanstowe** [comment]
I think panda at least ignores thhe NativeCall if it sees it, so no you're fine :)

**Comment by jonathanstowe** [comment]
Looks good.. Added,

**Pull request merged**
