### PR TITLE
hoelzro has switched linenoise to meta6.info

### PR DESCRIPTION
**Pull request by jantz**
Fix Task::Star build
https://github.com/hoelzro/p6-linenoise/commit/46f9534b1568e68a2a077ee80713914738b16e28

### CODE REVIEW

**Comment by LLFourn** [comment]
isn't it meant to be META6.json?

**Comment by jonathanstowe** [comment]
Yes it is, I'm not sure that this will work with e.g. panda that expects either the specced META6.json or the customary META.info.

**Comment by MadcapJake** [comment]
The commit shows that this actually was changed to the correct `META6.json`

**Comment by zoffixznet** [comment]
No, it doesn't. It was changed to META6**.info**

**Comment by MadcapJake** [comment]
Look at the commit given in the original PR.

**Comment by zoffixznet** [comment]
Ah, good eye and thanks for fixing it too. Cheers

**Pull request merged**
