### PR TITLE
Add Term::Choose::Util to ecosystem

### PR DESCRIPTION
**Pull request by kuerbis**
See https://github.com/kuerbis/Term-Choose-Util-p6

Add Term::TablePrint to ecosystem

See https://github.com/kuerbis/Term-TablePrint-p6

### CODE REVIEW

**Comment by jonathanstowe** [comment]
Thanks!

**Comment by ab5tract** [comment]
Just a heads up that other Terminal related packages are using Terminal::*
namespace. Fragmentation is inevitable, but just wanted to point it out.

**Comment by kuerbis** [comment]
"Term" is shorter, "Terminal::..." looks cumbersome to me or maybe its 
because I am to conservative.
But if there will be an agreement, I'll probably  change the name 
accordingly if necessary.

greetings
Matthäus

Am 16.03.2016 um 16:22 schrieb ab5tract:

**Comment by ab5tract** [comment]
The reasoning behind this is that 'term' has a quite specific meaning in
the Perl 6 language itself, and maybe the 'Term' namespace would be better
left to cater to modules relating to the language concept.

But I'm also on the opposite side of the naming spectrum than many people
(I hate abbreviations in module names). So it's really up to you.

**Pull request merged**
