### PR TITLE
Add update for Ddt to v0.5.3

### PR DESCRIPTION
**Pull request by kalkin**
See https://github.com/kalkin/Ddt

Thank you for submitting a module to the Perl 6 Ecosystem!

[Uploading Perl 6 modules to CPAN](https://docs.perl6.org/language/modules#Upload_your_Module_to_CPAN) is the preferred way of distributing modules, since GitHub is not a CDN. If you have the option, please use that route instead of adding the module here.

If adding a new module please review the following check boxes and check the appropriate boxes by going to the preview tab and checking them interactively or alternatively replacing the space in the checkboxes with an X. Your work is appreciated and every module helps make the Perl 6 Ecosystem a bigger and better place ♥

- [X] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by JJ** [comment]
Is there some reason why different versions of Ddt are included in META.list? Wouldn't it be better to just have the version number in META6.json in the main directory.

**Comment by kalkin** [comment]
AFAIK this is (was?) a common tactic to offer all different versions of a package to the user.

**Comment by JJ** [comment]
I wouldn't say that's the case anymore. I only see different versions of this module. There are other mechanisms, which are probably preferred, to do this, such as using different `:api` within the same module.

**Comment by ugexe** [comment]
Lets stop speculating on how the ecosystem works -- its *extremely* easy to test and see that its perfectly fine to have multiple urls in META.list. I challenge anyone to tell me why this would not be considered valid.

**Pull request merged**
