### PR TITLE
Move Zoffix Modules to Community

### PR DESCRIPTION
**Pull request by zoffixznet**

### CODE REVIEW

**Comment by jonathanstowe** [comment]
On a somewhat related note, do we feel that we should create some "perl6 community" PAUSE account so that we can put them on CPAN at some point?

**Comment by zoffixznet** [comment]
@AlexDaniel FYI: I did **not** update source URLs in META files in any of those modules

**Comment by JJ** [comment]
@jonathanstowe as long as this way of dealing with modules is OK, I don't see the need. But if you feel it's going to be better for some reason, just open an issue here and let's talk about it.

**Comment by JJ** [comment]
@zoffixznet we can do that, no problem. Thanks!

**Comment by AlexDaniel** [comment]
> On a somewhat related note, do we feel that we should create some "perl6 community" PAUSE account so that we can put them on CPAN at some point?

I don't think that “community-maintained” and “CPAN” is going to work well. Just leave them on github where everyone can contribute easily.

**Pull request merged**
