### PR TITLE
Add Sparrowdo::Chef::Client to ecosystem

### PR DESCRIPTION
**Pull request by melezhik**
Run chef client on remote host using Sparrowdo.

### CODE REVIEW

**Comment by zoffixznet** [comment]
Thanks.

P.S.: META.info is the old, pre-first-stable-release format. The new format for meta file is to be named META6.json. While we'll support both for probably quite a while, it'd be nice not to let the outdated name spread around.

**Comment by melezhik** [comment]
Hi @zoffixznet , sure will change the name to META6.json soon. If the *content* of the file is ok ?

**Comment by zoffixznet** [comment]
The content is fine, yes.

**Comment by melezhik** [comment]
Ok, good . Thanks.

**Pull request merged**
