### PR TITLE
Add perl6-CommonMark

### PR DESCRIPTION
**Pull request by drforr**
Thank you for submitting a module to the Perl 6 Ecosystem!

[Uploading Perl 6 modules to CPAN](https://docs.perl6.org/language/modules#Upload_your_Module_to_CPAN) is the preferred way of distributing modules, since GitHub is not a CDN. If you have the option, please use that route instead of adding the module here.

If adding a new module please review the following check boxes and check the appropriate boxes by going to the preview tab and checking them interactively or alternatively replacing the space in the checkboxes with an X. Your work is appreciated and every module helps make the Perl 6 Ecosystem a bigger and better place ♥

- [X] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by drforr** [comment]
This also requires libcmark - the CommonMark C library - to be installed - I don't think I've added the proper Travis invocation, I'll fix that on the morrow.

**Comment by moritz** [comment]
Any reason you add the module here instead of uploading it to PAUSE?

**Comment by drforr** [comment]
I did both, actually. I didn't want to assume that modules.perl6.org picked up new modules automatically, so I made sure to do both places. Since it won't show up in CPAN/metaCPAN I put the Pause listing below.

From PAUSE:
 Perl6/CHECKSUMS                                        981  Sun, 25 Feb 2018 21:53:37 GMT
 Perl6/CommonMark-0.0.3.meta                            664  Sun, 25 Feb 2018 21:07:57 GMT
 Perl6/CommonMark-0.0.3.readme                          666  Sun, 25 Feb 2018 21:07:57 GMT
 Perl6/CommonMark-0.0.3.tgz                          446040  Sun, 25 Feb 2018 21:14:14 GMT

**Comment by moritz** [comment]
FWIW the PAUSE upload worked; [modules.perl6.org](http://modules.perl6.org/dist/CommonMark:cpan:JGOFF) picked it up, and a `zef update; zef install CommonMark` gets as far as dying because `libcmark.so` is missing. I'd recommend not doing both, as it'll just cause confusion.

**Comment by drforr** [comment]
I'll close this PR then since it's already been picked up.

**Pull request closed without merging**
