### PR TITLE
add Proc::Async::Timeout

### PR DESCRIPTION
**Pull request by gfldex**

### CODE REVIEW

**Comment by zoffixznet** [comment]
The source-url contains a 404 URL; this won't be installable.

Also, it's recommended you add a non-empty `description` and the mandatory `perl` field that specifies the mimum Perl 6 version the module works with (e.g. `"perl": "6.*"`)

**Comment by zoffixznet** [comment]
I've sent you an invite to perl6 org. You can merge this PR yourself once the issues are fixed.

**Comment by gfldex** [comment]
`source-url` is fixed, `perl` is at `6.c` already.
I have filed issues with Test::META to warn on empty `description` and to check URLs.

Please do not send my anymore invites. After considerable consideration I have decided not to be part of the github Perl 6 org anymore.

**Comment by zoffixznet** [comment]
Thanks.

**Pull request merged**
