### PR TITLE
Add Math::Primesieve to ecosystem

### PR DESCRIPTION
**Pull request by CurtTilmes**
See https://github.com/CurtTilmes/perl6-primesieve

Thank you for submitting a module to the Perl 6 Ecosystem!

If adding a new module please review the following check boxes and check the appropriate boxes by going to the preview tab and checking them interactively or alternatively replacing the space in the checkboxes with an X. Your work is appreciated and every module helps make the Perl 6 Ecosystem a bigger and better place ♥

- [ X ] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).

- [ X ] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by the-eater** [comment]
This packages depends on a library, which as you may guess from the log, is not installed on the test server, since there is no good solution for requiring shared libs, it's pretty hard to detect such and install the required packages. Or even detect that the build fails because of missing libs.

On 2 May 2017 07:21:18 CEST, "Juan Julián Merelo Guervós" <notifications@github.com> wrote:
>JJ requested changes on this pull request.
>
>The CI has detected an error in the META6.json file. Can you please
>check it out? I can't figure it out by myself. 
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/perl6/ecosystem/pull/333#pullrequestreview-35699285

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JJ** [comment]
That's one of the errors, line 1202 far as I see it. I was talking about the one in line 1232. 
    
    not ok 1 - Checking correctness of https://raw.githubusercontent.com/CurtTilmes/perl6-primesieve/master/META6.json

Did you check that the JSON was correct?

The one in 1202 might be also an issue. Can you please check it?

**Comment by the-eater** [comment]
"Check if package tests pass" is a part of the subtest "Checking correctness of https://raw.githubusercontent.com/CurtTilmes/perl6-primesieve/master/META6.json", so it says it fails that because the child test of that subtest failed (still makes sense? Good.)

If the JSON wasn't correct it would've failed way earlier.

**Comment by JJ** [comment]
OK, I see your point, but you are right about the fact that there is no good way to specify external dependencies so the test still fails and will probably fail if someone tries to install this via zef. I would be more comfortable with someone else accepting this PR. Meanwhile, you can go to the IRC channel to see if there's a good workaround this for the time being.

**Comment by moritz** [comment]
Thanks @CurtTilmes, and welcome to the club!

**Pull request merged**
